#!/bin/bash

set -e  # Exit on error

# Define the system user name
SYS_USER="node-exporter"

case "$1" in
    configure)
        if ! getent group $SYS_USER > /dev/null; then
            echo "Creating group $SYS_USER."
            groupadd --system $SYS_USER
        fi

        if ! getent passwd $SYS_USER > /dev/null; then
            echo "Creating user $SYS_USER with home /var/lib/${SYS_USER}."
            useradd --system -g $SYS_USER --home-dir /var/lib/$SYS_USER --create-home $SYS_USER
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        # Actions if something goes wrong
        systemctl daemon-reload
        ;;
esac

exit 0